/*
 * Controller.java
 *
 * Created on Dec 15, 2010, 10:04:22 AM
 */


import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.beans.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Demo of controlling VLC from jAER project.
 *
 * @author Tobi
 */
public class Controller extends javax.swing.JFrame implements PropertyChangeListener {

    private VLCControl vlc = new VLCControl();
    private static Logger log = Logger.getLogger("Controller");

    /**
     * Creates new form Controller
     */
    Controller() {
        initComponents();
        vlc.getSupport().addPropertyChangeListener(this);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                //TODO
            }

            @Override
            public void windowClosing(WindowEvent e) {
                //TODO
            }

            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    vlc.disconnect();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }

            @Override
            public void windowIconified(WindowEvent e) {
                //TODO
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                //TODO
            }

            @Override
            public void windowActivated(WindowEvent e) {
                //TODO
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                //TODO
            }
        });

        name = new javax.swing.JTextField();
        UID = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VLCControl");

        name.setText("Name");
        name.setToolTipText("enter your name here");
        UID.setText("Some unique ID (same for partner)");
        UID.setToolTipText("Enter a unique id here");

        connectButton.setText("Connect");
        connectButton.addActionListener(evt -> connectButtonActionPerformed());


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(connectButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        )
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(connectButton)
                                )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void connectButtonActionPerformed() {
        MQTTHelper.run(UID.getText(),name.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Controller().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField name;
    private javax.swing.JTextField UID;
    private javax.swing.JButton connectButton;
    //private javax.swing.JButton disconnectButton;
    //private javax.swing.JScrollPane jScrollPane1;
    //private javax.swing.JTextArea responseTA;
    // End of variables declaration

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(VLCControl.CLIENT_MESSAGE)) {
            if (evt.getNewValue() != null) {
                String s = (String) evt.getNewValue();
                //responseTA.append(s);
                //responseTA.setCaretPosition(responseTA.getText().length());
            }
        }
    }

}
